version: "3.2"
services:
  auth-svc:
    command: node src/server.js
    build:
      context: ./auth-svc
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: astring
  movie-api:
    command: nodemon src/server.js -L
    build: ./movie-api
    volumes:
      - D:/Strony/nodejs-recruitment/movie-api/src:/app/src
      - ./tests:/tests
    environment:
      JWT_SECRET: astring
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    depends_on:
      - database
  database:
    build:
      context: prepared-db
      dockerfile: Dockerfile
    ports:
      - 5000:3000