version: "3.2"
services:
  auth-svc:
    command: node src/server.js
    build:
      context: ./auth-svc
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - ./auth-svc:/auth-svc/
    environment:
      JWT_SECRET: astring
  movie-api:
    command: node src/server.js
    build:
      context: ./movie-api
      dockerfile: Dockerfile
    volumes:
      - ./auth-svc:/auth-svc/
    environment:
      JWT_SECRET: astring
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    depends_on:
      - database
  database:
    build:
      context: prepared-db
      dockerfile: Dockerfile
    ports:
      - 5000:3000