version: "3.2"
services:
  app:
    command: node src/server.js
    build:
      context: ./auth-svc
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/auth-svc/
    environment:
      JWT_SECRET: astring
