POST localhost:3000/auth
Content-Type: application/json

{
  "id": 123,
  "role": "basic",
  "name": "Basic Thomas",
  "username": "basic-thomas",
  "password": "sR-_pcoow-27-6PAwCD8"

}
###
GET localhost:3001