POST localhost:3001/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEyMywibmFtZSI6IkJhc2ljIFRob21hcyIsInJvbGUiOiJiYXNpYyIsImlhdCI6MTYxMzQxMzc3MCwiZXhwIjoxNjEzNDE1NTcwLCJpc3MiOiJodHRwczovL3d3dy5uZXRndXJ1LmNvbS8iLCJzdWIiOiIxMjMifQ.PtSBH_ZmQh960CJ0b423a4KfWby-Um0X0_EGx-JAiPo
Content-Type: application/json

{
  "tittle": "terminator"
}

###
POST localhost:3000/auth
Content-Type: application/json

{
  "username": "basic-thomas",
  "password": "sR-_pcoow-27-6PAwCD8"
}

###
GET localhost:3001/a

###


