POST localhost:3001/movies
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQzNCwibmFtZSI6IlByZW1pdW0gSmltIiwicm9sZSI6InByZW1pdW0iLCJpYXQiOjE2MTM1OTE4OTcsImV4cCI6MTYxMzU5MzY5NywiaXNzIjoiaHR0cHM6Ly93d3cubmV0Z3VydS5jb20vIiwic3ViIjoiNDM0In0.JrWLl-d5r1l13ymC26XRm1IzEW4RGAKLYsuNTcsN8KY
Content-Type: application/json

{
  "tittle": "terminator"
}

###
POST localhost:3000/auth
Content-Type: application/json

{
  "role": "premium",
  "name": "Premium Jim",
  "username": "premium-jim",
  "password": "GBLtTyq3E_UNjFnpo9m6"
}

###
GET localhost:3001/a

###


